### ISSUE TITLE
Consider to replace Compass against libsass

### ISSUE THREAD

**Issue by jrief** [divio/django-cms#3600]
This would have many advantages:

 * Faster compilation times, some say up to 11x faster.
 * No need for Ruby gems and that stuff, everything is installable through ``pip``.
 * Files ending in ``.scss`` are referenced directly in the templates, rather than having to refer an autogenerated css-file.
 * Only one file has to be revisioned in *git*: the scss-file. The css file is generated on the fly and kept in the compressors cache.
 * No daemon, watching a subtree of the filesystem, must be started. The library django-compress and libsass will handle everything for us.

For more information refer to this post: https://groups.google.com/forum/#!topic/django-cms/KO7K1iMIjmo

**Comment by jrief** [comment]
@ojii so, what you say is, that there will not be any solution in the near future which can use django-compress with Sekizai.

Ok, then we have to reconsider option 1 again, or drop that feature completely.
Since that would be rather sad, I would like to emphasize again, that adding ``libsass`` to the dependency stack does not enforce anyone to use SASS instead of his preferred preprocessor such as LESS or STYLUS. They can coexists very well side by side. Its even beneficial, because then the users of, say LESS, simply have to add their preprocessor to the list of ``COMPRESS_PRECOMPILERS ``.

**Comment by ojii** [comment]
> @ojii so, what you say is, that there will not be any solution in the near future which can use django-compress with Sekizai.

Just for clarification, you *can* use django-sekizai with django-compressor, the amazing folks over at compressor made that happen. What is not possible at the moment is offline compression because of technical (how compressor looks for files to offline compress) and logical (way of how sekizai is intended to be used) reasons.

I know offline compression + sekizai is an important topic to people, but I have no answer for it at the moment. I'd be very interested in actual solutions (proposed or implemented) for this, but let's discuss this over on the django-sekizai tracker (if you happen to have a solution).

**Comment by jrief** [comment]
We now have a solution to solve this:
https://github.com/ojii/django-sekizai/pull/41

**Comment by jrief** [comment]
## django-sekizai-processors

I just released a package to do the ``*.scss`` to ``*.css`` conversion using Sekizai's templatetag ``addtoblock``.
Additionally all referred ``*.scss`` files can be compiled offline, using ``./manage.py compilescss`` and hence deployed onto production systems without the need of **libsass**.

Additionally it adds a sourcemap to each compiled file, so that when using element inspection on modern browsers, the source file is referred instead of the compiled css file.

For details, please see here: https://pypi.python.org/pypi/django-sekizai-processors/0.1.0

**This means, we now could start to migrate django-cms to use **libasss** exclusively, instead of Ruby SASS**

**Comment by yakky** [comment]
\O/ great job @jrief !

**Comment by FinalAngel** [comment]
So after digging into deeper:

I will start now on a libsass branch where I migrate accordingly. Though using ``django-libsass`` is the wrong package for the job. In case of the CMS, we compile it on release and package it within the CMS. 

Backing the django stack on the libsass compilation is the wrong move, we need to include a node / gulp (or Grunt) kinda way to compile, minify, concatenate, lint and optimise the generated output. Frontend developers are far more comfortable working in that environment. Additionally we need autoprefixer support to take care of the lack of mixins on the libsass front, there is not yet a solution for django there.

Also considering all the other advantages which we get through node such as linting and at some point testing. I'll reference my efforts to this issue.

**Comment by yakky** [comment]
Agree. Decoupling the CMS deployment from any specific way to generate and serve assets it's the only viable option, while still having a more integrated option is a very welcome addition

**Comment by FinalAngel** [comment]
Checkout https://github.com/FinalAngel/django-cms/pull/6/

**Comment by jrief** [comment]
May I remind to evaluate this package: https://github.com/jrief/django-sass-processor
@yakky had a concern to not install libsass on the server, therefore I wrote this package. It is able to combine the compilation with compression and the concatenation step.
During development I serve all CSS files with a sourcemap making SCSS debugging a piece of cake and during production I deliver only one CSS file, which has been pre-compiled on the development host.

**Comment by FinalAngel** [comment]
@jrief though it has some downsides:

- no autoprefixer support (which is a must, libsass without it is half the cake)
- no live-reload capabilities (which can easily be handled over the npm ecosystem)
- very good on a project level, but not for django-cms (as we ship the cms with precompiled css anyways)

things I'm not sure of:

- speed might be affected as you add additional static finders and tags
- whats the gain over ``django-libsass`` which seems for me to be simpler to understand

**Comment by jrief** [comment]
@FinalAngel 
* what do you mean by autoprefixer support? BTW, I currently use this library together with the SASS- port from Bootstrap installed via ``npm`` into a local ``node_modules``.
* live-reload could be added directly into Django using websockets. I made this proposal to @intellectronica in another context, but got no answer until now. The benefit would be, that you then don't need any nodejs process running side by side and that you could also use it on template and code changes. Lets discuss about that.

* Speed would only be problem during development. But I didn't measure any difference.
* With ``django-libsass`` you can't precompile css and you don't get any sourcemaps.

**Comment by FinalAngel** [comment]
@jrief just to answer your points

- autoprefixer: https://github.com/postcss/autoprefixer
- live-reload: well we want it sooner than later and there are plenty options for node
- speed: alright, still cautious about if it won't affect the live env as well
- django-libsass: sourcemaps can be generated through ``LIBSASS_SOURCE_COMMENTS``

anyhow, my proposal goes towards the node integration in https://github.com/FinalAngel/django-cms/pull/6. Using the right tool for the right job ;)

**Comment by driesdesmet** [comment]
However supportive I would be if you could use a python only solution, after much tinkering with different methods (sekzai/django-compressor, django-bower and the like) I'm glad @FinalAngels' branch proposes the gulp
route. The python ecosystem is just not at the same level at the moment for front-end stuff. That doesn't put out my hope for improvement, but it's the right path for noe I think.

**Comment by jrief** [comment]
@driesdesmet https://github.com/jrief/django-sass-processor is a pure Python approach. That's the reason I wrote it. The second reason was, that I dislike having to run a daemon, watching some directories and then acting.
I agree with @FinalAngel that autoprefixer and live-reload are a cool features. While live-reload can be integrated into Django quite easily, autoprefixer is more tricky.

**Comment by FinalAngel** [comment]
done :)
