### ISSUE TITLE
Support prefix_default_language = False

### ISSUE THREAD

**Issue by tgckpg** [divio/django-cms#6448]
### Summary
When
`i18n_patterns( prefix_default_language = False )`

Page redirect settings do not work properly on the default language.

Problematic file:
```
Calls:
0 cms/views.py: def details( ... )
1 cms/views.py: if (is_language_prefix_patterns_used() ...
2 cms/utils/i18n.py: def is_language_prefix_patterns_used => True ( should be False on default language )
```

Reference fix:
`django/conf/urls/i18n.py: def is_language_prefix_patterns_used`

### Expected behaviour
On default language, page should be redirected without language prefix.

### Actual behaviour
On default language, page redirects with language prefix.

### Environment

* Python version: 3.6.0
* Django version: 1.11.7
* django CMS version: 3.4.6

**Comment by nabinbhusal80** [comment]
I faced the same problem as well. The redirection does not work. If always sticks to the first language that is input and no changes take place after that.

**Comment by tgckpg** [comment]
Since the devs didn't respond for a long time and the issue is rather critical IMO...

So here's the monkey patch I've written for anyone who come across this issue.

Place this under `urls.py` ( or some other better places ).
```python
from cms import views as cms_views
from django.urls import LocaleRegexURLResolver, get_resolver
def _patch_lang_pfx():
    for url_pattern in get_resolver(None).url_patterns:
        if isinstance(url_pattern, LocaleRegexURLResolver):
            return url_pattern.prefix_default_language
    return False
# Swap out the faulty method from cms.views
cms_views.is_language_prefix_patterns_used = _patch_lang_pfx
```

**Comment by ivanfr90** [comment]
I'm suffering the same. 
Redirections always go to the path language without keep in mind if `prefix_default_language` is configured in url's definition.

**Comment by jscontrust** [comment]
Same here. Would be great to have the `prefix_default_language` option implemented to django cms

**Comment by tgckpg** [comment]
Thanks! Issue is fixed in 3.7.0. I am closing this now.

**Comment by Zeerooth** [comment]
Unfortunately this still hasn't been fixed as of django-cms 3.7.1, django 2.2.11 and python 3.7. Redirects append the language prefix to urls even if prefix_default_language=False

Here are my url settings: 
```
urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    url(r'^', include('cms.urls')),
    url(r'^', include('filer.server.urls')),
    prefix_default_language=False,
)
```

I can't test @tgckpg monkeypatch anyway as LocaleRegexURLResolver was removed in Django 2.0
I hope this will be fixed in foreseeable future

**Comment by tgckpg** [comment]
> I can't test @tgckpg monkeypatch anyway as LocaleRegexURLResolver was removed in Django 2.0
> I hope this will be fixed in foreseeable future

Oh cms support django 2.0 now!? Waited for so long that I've already forgot. I'll have to check if we could upgrade it first. Since we have **so many** monkey patches for cms & django itself, might take quite some time to re-evaluate.

Will get back to you...in a month maybe? If the issue persist I'll have to write another monkey patch anyway. But I think the idea of mitigating `is_language_prefix_patterns_used ` should just be the same.

**Comment by tgckpg** [comment]
@Zeerooth Wait sorry I was being dumb. We're already at the latest release. So the issue should've been fixed. You may need to reinstall the package from pip.

By checking the latest `cms/views.py`, you should see they've patched the issue with this piece of code:
```python
def _clean_redirect_url(redirect_url, language):
    if (redirect_url and is_language_prefix_patterns_used() and redirect_url[0] == "/"
            and not redirect_url.startswith('/%s/' % language)):
        # add language prefix to url
        redirect_url = "/%s/%s" % (language, redirect_url.lstrip("/"))
    return redirect_url
```

[Reference](https://github.com/divio/django-cms/blob/release/3.7.x/cms/views.py#L30)

**Comment by Zeerooth** [comment]
@tgckpg Thanks for the reply!

I haven't really looked at this thread for a few days but now I've got some more data

First of all, what you're saying is correct, I looked at the code and the patch *should* work correctly after all, but something's still not right - I don't know if it is either a bug or a problem with my config.

In my dev environment, in `def is_language_prefix_patterns_used():` I tried listing every url_pattern to see if any and if so, which are an instance of LocalPrefixPattern. Here are the examples:
```
(is instance of LocalePrefixPattern?) <URLResolver <module 'apps.forms.urls' from '/path/to/my/apps/forms/urls.py'> (forms:apps.forms) 'forms/'>: False
(is instance of LocalePrefixPattern?) <URLResolver <module 'apps.newsletter.urls' from '/path/to/my/apps/newsletter/urls.py'> (newsletter:apps.newsletter) 'newsletter/'>: False
(is instance of LocalePrefixPattern?) <URLResolver <module 'apps.faq.urls' from '/path/to/my/apps/faq/urls.py'> (faq:apps.faq) 'faq/'>: False
(is instance of LocalePrefixPattern?) <URLResolver <module 'apps.stats.urls' from '/path/to/my/apps/stats/urls.py'> (stats:apps.stats) 'stats/'>: False
(is instance of LocalePrefixPattern?) <URLResolver <module 'apps.statistics.urls' from '/path/to/my/apps/statistics/urls.py'> (statistics:apps.statistics) 'statistics/'>: False
(is instance of LocalePrefixPattern?) <URLResolver <URLPattern list> (admin:admin) 'admin/'>: False
(is instance of LocalePrefixPattern?) <URLResolver <URLResolver list> (None:None) ''>: True
```

Now, for some reason every attribute 'pattern' of url_pattern is listed as not instance of LocalePrefixPattern but there is one instance of <URLResolver <URLResolver list> (None:None) ''> which ends up as a correct instance thus returning True from `is_language_prefix_patterns_used()` and `_clean_redirect_url` returns an url with prefix.

I'll try to investigate this issue further but for now this is all I got.

**Comment by tgckpg** [comment]
I suspect that your `urls.py` maybe misconfigured. I think the module you've listed which returned `False` are not provided by CMS. Hence they're out of CMS`s scope. So I'm not clear if your issues is related to the one I posted here. ( I was referring to the CMS's static page were not redirecting properly. )

Anyway, here's some examples from our repo:
`website/urls.py` ( entrance `urls.py` )
```python
urlpatterns = i18n_patterns(
    path( "auth/", include( "my_auth.urls" ) )
    , prefix_default_language = False
)
```

`my_auth/urls.py`
```python
from django.urls import path
from . import views

urlpatterns = [
    path( 'login/', views.login, name = "my_auth.login" )
]
```

**Comment by Zeerooth** [comment]
@tgckpg thank you for those examples!

I tried using a barebones setup for my app with all unnecessary INSTALLED_APPS removed and only urls that are required by django/django-cms, like this:
```python
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns

app_name = "my_app"

urlpatterns = i18n_patterns(
    url(r'^', include('cms.urls')),
    path('admin/', admin.site.urls),
    prefix_default_language=False,
)
```

I also created a new django-cms project using the installer and yet, still, the result is the same : /
I don't know, maybe the problem is somewhere in the dependencies? But I doubt it

**Comment by tgckpg** [comment]
The `cms.urls` should be at the bottom of the i18n_pattern for catch all to be effective:
```python
urlpatterns = i18n_patterns(
    path('my-thing/', include('my_things.urls')),
    path('admin/', admin.site.urls),
    path('', include('cms.urls')),
    prefix_default_language=False,
)
```

**Comment by Zeerooth** [comment]
@tgckpg thanks for the help but I tried to change my settings to that hierarchy and the problem still persists

**Comment by tgckpg** [comment]
Sorry I couldn't help. But here's a gif I've recorded of it working fine. As you can see the "en" is hidden and is redirecting properly.
![working-fine](https://user-images.githubusercontent.com/5273654/78772864-f9387880-79c4-11ea-9b0b-4fc9156c9736.gif)

**Comment by Zeerooth** [comment]
@tgckpg No problem, sorry for writing after such a long time but could you try one thing? 
First, let's say that your page's default language is A and your browser is in language B (English in my case)
Then, change the configuration so that language A is the primary language and prefix_default_language in URLs is set to True
Add language B to your configuration so that you'll have a prefix
Then, change slugs in the "aaaa" page to be different and then try to change languages 

Now redirects and don't work and you can't even enter (as a user) any page in language A because of how Django path resolving works - let's say you have the following pages:
/aaa (default language)
/B/bbb (same page, different slug and language)
Now, when going to /aaa Django will set B as your ```request_language``` because the prefix is missing so it tries to read the language of your browser. It finds that B is your browser's language so it redirects you to page /B/bbb and there you go.

Now, why doesn't it happen when slugs are the same? Well, this is because how django-cms decides when to redirect you do different pages, look at this (django-cms 3.7.2):

cms.views.details(request, slug)
```
page_path = page.get_absolute_url(request_language)
page_slug = page.get_path(request_language) or page.get_slug(request_language)

if slug and slug != page_slug and request.path[:len(page_path)] != page_path:
      # The current language does not match its slug.
      # Redirect to the current language.
      return HttpResponseRedirect(page_path)
```

When the slugs are the same both slug and page_slug variable will actually equal the same variable because get_path() actually ignores the prefix from language and returns absolute path, therefore making them equal and the redirect doesn't happen.

Now is it intentional behaviour? Could be, although I think this is extremely unreliable and may lead to situations like mine - that clients with different browser languages can't enter other language pages because cms redirects them automatically to a page that is in their default language which is just plain bad user experience needing a fix.

(There is also a Django ticket that describes similar issue here https://code.djangoproject.com/ticket/29425 and the conclusion was that it was the intended behaviour although you can clearly see that it leads to bugs and confusion)

**Comment by tgckpg** [comment]
Yeah I think you are describing the issue #6742...and you were there? It's still open so you may try the patch I mentioned over there.

**Comment by Zeerooth** [comment]
@tgckpg Thanks! I mean, the patch works I guess, even without the one being applied directly to Django (I think they must have fixed it in newest releases) but I don't really like the solution because it messes up the cache and causes the tests to fail so... It may be a solution for now but I'll try to think of something more permanent
