### ISSUE TITLE
ImportError: cannot import name 'EMPTY_VALUES' from 'django.forms.fields'

### ISSUE THREAD

**Issue by AhmedSalam22** [divio/django-cms#6892]
## Description
Issue when installing Django-CMS Manually

http://docs.django-cms.org/en/latest/how_to/install.html#using-cms-check-for-configuration
## Steps to reproduce
I just follow the documentation as it is

## Additional information
I use Django 3.1
![Screenshot (295)](https://user-images.githubusercontent.com/35177448/91569120-fd4e3e00-e945-11ea-800b-5c53d48c2e90.png)

**Comment by AhmedSalam22** [comment]
I have changes to Django 3.0 but new problem appears 

![Screenshot (296)](https://user-images.githubusercontent.com/35177448/91578426-7059b380-e94a-11ea-8eef-cff29a52ed7c.png)

**Comment by yakky** [comment]
This is fixed by #6886

**Comment by AhmedSalam22** [comment]
> This is fixed by #6886

what about this error ?
django\apps\config.py", line 142, in create if not issubclass(cls, AppConfig): TypeError: issubclass() arg 1 must be a class

**Comment by FinalAngel** [comment]
closing as reported in https://github.com/divio/django-cms/issues/6893

**Comment by bittner** [comment]
I can still reproduce the original error from above with the current stable version 3.7 of django CMS. See https://github.com/Organice/djangocms-maps/pull/20#issuecomment-803605341.

IIUC from https://github.com/django-cms/django-cms/issues/6893#issuecomment-705234405, there will be no backport of the fix for django CMS 3.7. Hence, Django 3.1 is supported by django CMS 3.8+ only?
